CREATE DATABASE dbHospital
GO

USE dbHospital
GO

-- Esquema Paciente
CREATE SCHEMA Paciente
GO

-- Esquema Medico
CREATE SCHEMA Medico
GO

-- Esquema Historia
CREATE SCHEMA Historia
GO

-- CREAR TABLA PACIENTE
CREATE TABLE Paciente.Paciente
(
	CODPAC INT NOT NULL IDENTITY(1,1),
	NOMPAC VARCHAR(120) NOT NULL,
	APEPATPAC VARCHAR(120) NOT NULL,
	APEMATPAC VARCHAR(120) NOT NULL,
	FECNACPAC DATE NOT NULL, 
	SEXPAC CHAR(1) NOT NULL,
	DNIPAC CHAR(8) NOT NULL,
	TELEFPAC VARCHAR(9),
	EMAILPAC VARCHAR(100),
	DOMPAC VARCHAR(120) NOT NULL,
	UBIGEOPAC CHAR(6) NOT NULL,
	FECREGPAC DATETIME,
	OBSERPAC VARCHAR(250),
	CONSTRAINT PK_CODPAC PRIMARY KEY(CODPAC)
)
GO

-- CREAR TABLA HISTORIA PACIENTE
CREATE TABLE Paciente.Historia_Paciente
(
	CODHIST INT NOT NULL,
	CODPAC INT NOT NULL, 
	CODMED INT NOT NULL, 
	CONSTRAINT PK_HISTORIA_PACIENTE PRIMARY KEY(CODHIST, CODPAC, CODMED)
)
GO

-- CREAR TABLA UBIGEO
CREATE TABLE Paciente.Ubigeo
(
	CODUB CHAR(6) NOT NULL,
	DISTUB VARCHAR(60),
	PROVUB VARCHAR(60),
	DEPUB VARCHAR(60),
	CONSTRAINT PK_CODUB PRIMARY KEY(CODUB)
)
GO

-- CREAR TABLA TURNO PACIENTE
CREATE TABLE Paciente.Turno_Paciente
(
	CODTUR INT NOT NULL,
	CODPAC INT,
	CODMED INT,
	CONSTRAINT PK_TURNO_PACIENTE PRIMARY KEY(CODTUR, CODPAC, CODMED)
)
GO

-- CREAR TABLA MEDICO
CREATE TABLE Medico.Medico
(
	CODMED INT NOT NULL IDENTITY(1,1),
	NOMMED VARCHAR(120) NOT NULL,
	APEPATMED VARCHAR(120) NOT NULL,
	APEMATMED VARCHAR(120) NOT NULL,
	FECNACMED DATE NOT NULL, 
	SEXMED CHAR(1) NOT NULL,
	DNIMED CHAR(8) NOT NULL,
	TELEFMED VARCHAR(9),
	EMAILMED VARCHAR(120),
	DOMMED VARCHAR(120) NOT NULL,
	UBIGEOMED CHAR(6) NOT NULL,
	FECREGMED DATETIME,
	OBSERMED VARCHAR(180),
	CONSTRAINT PK_CODMED PRIMARY KEY(CODMED)
)
GO

-- CREAR TABLA ESPECIALIDAD
CREATE TABLE Medico.Especialidad
(
	CODESP INT NOT NULL IDENTITY(1,1),
	NOMESP VARCHAR(80) NOT NULL,
	OBSESP VARCHAR(100),
	CONSTRAINT PK_CODESP PRIMARY KEY(CODESP)
)
GO

-- CREAR TABLA MEDICO ESPECIALIDAD
CREATE TABLE Medico.Medico_Especialidad
(
	CODMED INT NOT NULL,
	CODESP INT NOT NULL,
	DESESP VARCHAR(1000),
	CONSTRAINT PK_MEDICO_ESPECIALIDAD PRIMARY KEY(CODMED,CODESP)
)
GO

-- CREAR TABLA HISTORIA
CREATE TABLE Historia.Historia
(
	CODHIST INT NOT NULL IDENTITY(1,1),
	FECHIST DATETIME NOT NULL,
	OBSHIST VARCHAR(1800) NOT NULL,
	CONSTRAINT PK_CODHIST PRIMARY KEY(CODHIST)
)
GO

-- CREAR TABLA TURNO
CREATE TABLE Historia.Turno
(
	CODTUR INT NOT NULL IDENTITY(1,1),
	FECTUR DATETIME,
	ESTTUR SMALLINT,
	OBSTUR VARCHAR(500),
	CONSTRAINT PK_CODTUR PRIMARY KEY(CODTUR)
)
GO

-- RELACIONES
ALTER TABLE Paciente.Paciente
	ADD CONSTRAINT FK_PACIENTE_UBIGEO FOREIGN KEY (UBIGEOPAC)
	REFERENCES Paciente.Ubigeo(CODUB)

ALTER TABLE Medico.Medico_Especialidad
	ADD CONSTRAINT FK_MEDICO_ESPECIALIDAD_MEDICO FOREIGN KEY (CODMED)
	REFERENCES Medico.Medico(CODMED)

ALTER TABLE Medico.Medico_Especialidad
	ADD CONSTRAINT FK_MEDICO_ESPECIALIDAD_ESPECIALIDAD FOREIGN KEY (CODESP)
	REFERENCES Medico.Especialidad(CODESP)

ALTER TABLE Paciente.Turno_Paciente
	ADD CONSTRAINT FK_TURNO_PACIENTE_TURNO FOREIGN KEY(CODTUR)
	REFERENCES Historia.Turno(CODTUR)

ALTER TABLE Paciente.Turno_Paciente
	ADD CONSTRAINT FK_TURNO_PACIENTE_PACIENTE FOREIGN KEY(CODPAC)
	REFERENCES Paciente.Paciente(CODPAC)

ALTER TABLE Paciente.Turno_Paciente
	ADD CONSTRAINT FK_TURNO_PACIENTE_MEDICO FOREIGN KEY(CODMED)
	REFERENCES Medico.Medico(CODMED)

ALTER TABLE Paciente.Historia_Paciente
	ADD CONSTRAINT FK_HISTORIA_PACIENTE_PACIENTE  FOREIGN KEY(CODPAC)
	REFERENCES Paciente.Paciente(CODPAC)

ALTER TABLE Paciente.Historia_Paciente
	ADD CONSTRAINT FK_HISTORIA_PACIENTE_MEDICO FOREIGN KEY(CODMED)
	REFERENCES Medico.Medico(CODMED)

ALTER TABLE Paciente.Historia_Paciente
	ADD CONSTRAINT FK_HISTORIA_PACIENTE_HISTORIA FOREIGN KEY(CODHIST)
	REFERENCES Historia.Historia(CODHIST)

ALTER TABLE Medico.Medico
	ADD CONSTRAINT FK_MEDICO_UBIGEO FOREIGN KEY(UBIGEOMED)
	REFERENCES Paciente.Ubigeo

BACKUP DATABASE dbHospital
TO DISK = 'C:\dbHospital\dbHospital.bak'
GO